name:                sat-solver
version:             0.1.0.0
github:              "agentultra/sat-solver"
license:             BSD3
author:              "See CONTRIBUTORS.md"
maintainer:          "james@agentultra.com"
copyright:           "2023 James King"

extra-source-files:
- README.md
- CHANGELOG.md
- CONTRIBUTORS.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sat-solver#readme>

default-extensions:
- DeriveFunctor
- GeneralizedNewtypeDeriving
- OverloadedStrings
- TupleSections
- ScopedTypeVariables

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.7
- microlens
- microlens-mtl
- microlens-th
- mtl
- QuickCheck
- data-ordlist

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  sat-solver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - QuickCheck
    - sat-solver
